[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
clap = "2.34.0"

[dev-dependencies]
criterion = "^0.3.5"

[[bench]]
name = "benches"
harness = false
